name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  
  build:
    name: Build Image    
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: mlflow-server
      TAGS: v1 ${{ github.sha }}
      
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      # Setup S2i and Build container image
      - name: Setup and Build
        id: build_image
        uses: redhat-actions/s2i-build@v2
        with:
          path_context: 'mlflow-server'
          # Builder image for a java project
          builder_image: 'registry.access.redhat.com/ubi8/python-39:latest'
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.TAGS }}

      - name: image
        run: echo ${{ steps.build_image.outputs.image }}

      - name: Retrieve version
        uses: addnab/docker-run-action@v3
        with:
          images: ${{ steps.build_image.outputs.image }}
          run: |
            echo "::set-output name=FULL_VERSION::$(pip show mlflow | grep -i version | awk '{print $2}')"
        id: version

      - name: Retrieve version
        uses: addnab/docker-run-action@v3
        with:
          images: ${{ steps.build_image.outputs.image }}
          run: |
            FULL_VERSION=$(pip show mlflow | grep -i version | awk '{print $2}')
            major=`echo $FULL_VERSION | cut -d. -f1`
            minor=`echo $FULL_VERSION | cut -d. -f2`
            revision=`echo $FULL_VERSION | cut -d. -f3`
            MINOR_VERSION=$(echo "$major.$minor")
            echo "::set-output name=FULL_VERSION::${FULL_VERSION}"
            echo "::set-output name=FULL_VERSION::${MINOR_VERSION}"
        id: version

      - name: Full Version
        run: echo "${{ steps.version.outputs.FULL_VERSION }}"

      - name: Minor Version
        run: echo "${{ steps.version.outputs.MINOR_VERSION }}"

      # Push Image to Quay registry
      - name: Push To Quay Action
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: quay.io/troyer
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
