name: Push README to Quay.io
on:
  push:
    branches: [ main ]
    paths: 
      - 'README.md'

jobs:

  PushContainerReadme:
    runs-on: ubuntu-latest
    name: Push README to Quay.io
    env:
      REGISTRY: quay.io/jonkeyguan
      IMAGE_NAME: mlflow-server
    steps:
      - name: git checkout
        uses: actions/checkout@v2
      - name: push README to Quay.io
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_APIKEY: ${{ secrets.APIKEY__QUAY_IO }}
        with:
          destination_container_repo: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          provider: quay
          readme_file: 'README.md'
